FROM postgres:16

RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    python3-psycopg2 \
    patroni \
    patroni-etcd \
    && rm -rf /var/lib/apt/lists/*

COPY patroni-entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 5432 8008
ENTRYPOINT ["/entrypoint.sh"]
